[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_insurance_anchor = "2pKQm49tzqVabLeji328Gu8dE6HnYh5cWJUiBJDsAHA4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/stefan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
